//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsPayment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public int student_id { get; set; }
        public System.DateTime payment_date { get; set; }
        public decimal amount { get; set; }
        public int month { get; set; }
        public int year { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
